[phases.setup]
aptPkgs = [
    'gfortran',
    'libblas-dev', 
    'liblapack-dev',
    'build-essential',
    'pkg-config',
    'python3-dev'
]

[phases.install]
cmds = [
    'python3 -m pip install --upgrade pip setuptools wheel',
    'python3 -m pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = "python3 main.py"