[phases.setup]
# Install system dependencies including Fortran compiler
aptPkgs = [
    'gfortran',
    'libblas-dev', 
    'liblapack-dev',
    'build-essential',
    'pkg-config'
]

[phases.install]
# Upgrade pip and install with optimizations
cmds = [
    'pip install --upgrade pip setuptools wheel',
    'pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = "python main.py"